read_dir: "example"
bwa_index_algorithm: "bwtsw"
genome_url: "ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/017/985/GCA_000017985.1_ASM1798v1/GCA_000017985.1_ASM1798v1_genomic.fna.gz"
samtools_mem_alloc: "32G"